services:
  - type: web
    name: ai-sales-agent
    env: python
    plan: free
    region: ohio
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 src.app:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: SENDER_NAME
        sync: false
      - key: SENDER_EMAIL
        sync: false
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: MEETING_LINK
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.12
